### ISSUE TITLE
Add Wifi State to devices

### ISSUE THREAD

**Issue by skalavala** [skalavala/smarthome#17]
Extract Wifi state from Life360 data and add it to Owntracks device tracker, and write an automation that triggers when kids are home and have turned off WiFi on their cell phones.

**Comment by CCOSTAN** [comment]
Check out MeetCircle.com

**Comment by skalavala** [comment]
I implemented a custom Life360 sensor (in my repo) that gets the WiFi state of each device, and works great!

**Comment by CCOSTAN** [comment]
Have you seen this ?  Might fit right into what you are doing.. 

https://community.home-assistant.io/t/cut-internet-temporarily-in-a-device-in-your-lan
