### ISSUE TITLE
Multiple Circles breaks life360.py custom component

### ISSUE THREAD

**Issue by shaneapowell** [skalavala/smarthome#28]
I installed your life360.py custom component in my home assistant install.  At first, it failed to run with a very strange error. Simply reported that the curl failed for command3 with a "/bin/sh: line 1: 719f96f6-6d09-4125-bbca-2eb64a5d27a4: command not found"  Debugging the output of the various steps, it seems that the call to get the circles.json, piped through the grep, returned in my case, 2 circles, and as a result, it returned a pair of ids, one on each line.

[shane@castle ~]# curl -s -X GET -H "Authorization: Bearer OWZ....ZWE4" https://api.life360.com/v3/circles.json | grep -Po '(?<="id":")[\w-]*'
15b602....9564a5
719f96..4a5d27a4

As a result, the call to command3 thought there was a 2nd line in the command.  It would seem a loop on the pair of IDs might be necessary, or perhaps an optional "circle" field in the configuration to specify which circle to pull data from.

I removed my 2nd circle for now since it was not really needed, and all is working again.

**Comment by skalavala** [comment]
Thanks for pointing out.. I only have one circle, and never tested with multiple circles. will try that some time...

**Comment by Aephir** [comment]
Hi,

I am using [a different script](https://github.com/Aephir/HomeAssistant2/wiki/99.1---life360-script---Not-committed-to-github-due-to-sensitive-information-(removed-here)) to the same end (didn't make it myself, I got the original from brazen1445 in [this thread](https://community.home-assistant.io/t/life-360-support/1690/15)).

I have multiple (two) circles, and it works fine. However, every contact is in one single main circle, the second circle is just a subset of the first, so maybe this is not comparable?

In any case, maybe someone with a better understanding could get something from looking at both scripts?
