### ISSUE TITLE
palo alto sensor

### ISSUE THREAD

**Issue by darkstar939** [skalavala/smarthome#34]
I am running a Palo Alto VM-100 on my edge.  Can you walk me through briefly how to set up the custom palo sensor you wrote.

Thanks,

Jon

**Comment by skalavala** [comment]
Apologize for my delayed response. I thought I saw an issue, but never came back to respond. I wrote the custom component to get the basic details about the device and also have a few automations where I get notified every time someone logs into my firewall or my vpn (global protect). I also have a few scripts that I run to clear logs (threat logs, traffic logs...etc).

The way you do it is by generating the API key from your device, and specify the API KEY and the ipaddress and whether your device accepts SSL connections or not. Once you provide correct information, it then makes HTTP calls to your Palo Alto device and retrieves information at a specified interval. 

Follow the url to get your API key:
https://www.paloaltonetworks.com/documentation/71/pan-os/xml-api/get-started-with-the-pan-os-xml-api/get-your-api-key

You can then use that information in your automations and scripts.

The component should work with Palo Alto VMs as well, as there is not much difference from the appliance and the VM when it comes to the underlying software. Good luck!

**Comment by skalavala** [comment]
closing the issue.

**Comment by darkstar939** [comment]
Thanks!
