### ISSUE TITLE
Package birthday setup failed. Component input_label does not exist

### ISSUE THREAD

**Issue by poldim** [skalavala/smarthome#35]
Just wondering if this is a recent change that HA removed the input_label component? 

This is the closest I could find but it looks like it requires some modifications to your package yaml:
https://www.home-assistant.io/components/input_text/

**Comment by Norien** [comment]
I believe he is using a custom component for input_label.

https://github.com/skalavala/smarthome/tree/master/custom_components

**Comment by skalavala** [comment]
@poldim As Norien mentioned, I am using custom component for my birthday package. I have not upgraded to 0.73 yet, still running on 0.72.1, and works great. I will upgrade to 0.73 tonight and will verify it.

**Comment by skalavala** [comment]
Yes, just confirming that it works with 0.73 version.

**Comment by poldim** [comment]
Doooope, didn't realize that!  

Maybe I'm doing something wrong, but I can't get it to work.  I copied over `input_label.py` and `services.yaml` to the `custom_components` folder.  But it's not calculating the date, I've had it running for several days.

https://i.imgur.com/Wd3gUbV.png


Any chance you have any guidance?

**Comment by skalavala** [comment]
@poldim I just responded this to someone else, who ran into a similar problem. The birthday package uses `date` sensor. You need to have the following sensor somewhere for it to work.

```
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'
```

Add the above sensor in the birthday package and try again. It should work.

**Comment by poldim** [comment]
That was it!  I had the ```- platform: time_date
  display_options:
    - 'date_time'``` so it's odd that it didn't work until I added it to
the package.

Would be great if you update your package notes for future folks.  Thanks
for the nice work!

**Comment by skalavala** [comment]
I already did that last night! Glad it worked for you!
