### ISSUE TITLE
Life360 component

### ISSUE THREAD

**Issue by JamesMcCarthy79** [skalavala/smarthome#36]
Hi,

I am getting error I installed as per yours sensor always shows as error never changes state

```
Log Details (ERROR)
Fri Jul 13 2018 19:11:34 GMT+1000 (Australian Eastern Standard Time)

Life360 has not responsed well. Nothing to worry, will try again!
```

**Comment by skalavala** [comment]
Hello,

It could be several things - 

1) You are not properly authenticated - make sure the password doesn't contain characters like `# $ ' and "`
2) You also need OwnTracks setup in your configuration

3) Your MQTT should be set up as well.

From the Home Assistant server, you should be able to run the three commands from the CLI (just replace USERNAME360 and PASSWORD360 with your actual username and password. When you run the first command, it gives you the access token, and you take that access token and pass it to the subsequent commands to get the members and circles. 

The component only supports one circle for now, and haven't had a chance to modify it to suport multiple circles.

I am on Discord if you need real-time help.

**Comment by JamesMcCarthy79** [comment]
1. I don't have those characters in my password.
2. Owntracks has been set up and working for months
3. MQTT is setup and working 

I managed to add an automation to force owntracks updates and in conjunction with tasker have got owntracks to a reliable point so I will continue with this but I would have liked to get this component set up
