### ISSUE TITLE
Birthday Package - Unable to find component input_label

### ISSUE THREAD

**Issue by josephtpeterson** [skalavala/smarthome#37]
Hello,

I really appreciate that you have provided your HA layout and configurations. You have a lot of great ideas that I would like to implement. I think my family will enjoy the birthday package a lot. I followed the steps in the birthday.yaml file, and have tried using your files unedited, but I received the same error. After some digging, I see that some home assistant components names have changed and may need to be updated, but nothing referencing input_label. Here is the error.

[homeassistant.loader] Unable to find component input_label

Also, after adding the birthday package, I received an error when checking my configuration. If I comment outthe line  _automation: !include automations.yaml_ in my configuration.yaml, the error goes away.

Invalid config for [automation]: required key not provided @ data['action']. Got None
required key not provided @ data['trigger']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/automation/

Any help would be greatly appreciated, thank you for all your contributions.

Joe

**Comment by josephtpeterson** [comment]
And I just realized you have a custom component called input_label. :)

I will test with it in place now and report back.

-Joe

**Comment by josephtpeterson** [comment]
After adding the input_label.py and services.yaml file, birthday countdowns appear to be working in my HA.

As for the automations, how do I set it up properly to use automations within this package without adding all my automations to the birthdays.yaml.

Thank you again!

-Joe

**Comment by josephtpeterson** [comment]
@skalavala Wow, I have learned a great deal more about home assistant and with how I can use it just by going over your config. After reviewing your setup further, it dawned on me that I just needed to make a slight modification to my existing automation.yaml then move it into the packages folder. All is working well now. I will have to look into how you make notifications work later as well.

Thank you again for your contributions!

-Joe

**Comment by skalavala** [comment]
Sorry - I just saw your messages. Hope you got everything working! I have been away for the weekend!

**Comment by josephtpeterson** [comment]
Everything is working great! After seeing how you organize your config, the logic behind it just makes sense to me. I just didn't know you could do it that way. I liked it some much, I am in the process of re-organizing my config and converting many of my existing sensors, automations, etc into package yamls. So my easier to encapsulate and test/troubleshoot new configurations. 

Thank you again for all you have shared!

Joe
