### ISSUE TITLE
google home say a Daily Morning quote as a part of morning routine?

### ISSUE THREAD

**Issue by ceaswaran** [skalavala/smarthome#38]
Hi,
Not sure if this is the right way to communicate to you thru issues tab as i dint find alternate methods (email etc.,) hence am posting here, sorry

Saw ur repo https://github.com/skalavala/smarthome/blob/master/templates/birthday_wishes.yaml

**My Query:**

Is it possible to make google home say a Daily Morning quote as a part of morning routine?
I am thinking of a new quote everyday morning.

**Example:**  
**say I have stored say 10 mp3 files in my local location inside HassIO
I want them to play each one at random every morning. thru an automation/script.

Randomly played Day1 mp3 should not repeat for next 9 days, After 10th day the process repeats**

I run Home assitant on Raspberry pi 2. 

Am totally new to this HA stuff. Is it possible? If so please guide me how to configure it?

**Comment by skalavala** [comment]
You can always find/tag me in the Discord :)

To answer your question, yes, it can be done, and it is fairly easy to implement as well.

To ensure you re not repeating the old quote, you have to write code that remembers all the last 10 days quotes, as using `random` does not automatically make it different each day.
