### ISSUE TITLE
Question about garbage...

### ISSUE THREAD

**Issue by niemyjski** [skalavala/smarthome#39]
I was wondering how you were able to configure and set the recycling and garbage days. I selected them from the drop down and have everything configured (mqtt) but the days are always unknown...

**Comment by skalavala** [comment]
It must be that you do not have `datetime` sensor setup? The package uses that datetime sensor, and in my setup, it is in a different file. I am usually on Discord if you want to find me. I rarely check the issues on my github repo, you got lucky this time :)

**Comment by niemyjski** [comment]
Yes, I have them right here: https://github.com/niemyjski/home-assistant/blob/master/packages/garbage/garbage.yaml#L119

**Comment by niemyjski** [comment]
Had to do with Mqtt not supporting ssl

**Comment by skalavala** [comment]
@niemyjski Thanks for closing the issue. I just updated the package late last week, where I added additional conditions/messaging when both trash and recycle pickup happens to be on the same day.

**Comment by skalavala** [comment]
Sorry - I do not understand specifics about your setup and issues with your local MQTT. This component has been working well for me and for many. If it doesn't work, hit me up on Discord. Thanks!
