### ISSUE TITLE
Get ERROR 'trigger' is undefined

### ISSUE THREAD

**Issue by abeksis** [skalavala/smarthome#45]
I get the following error:

`Error rendering data template: UndefinedError: 'trigger' is undefined
`

my code:

https://gist.github.com/abeksis/f4272865a9759a18b958798920632e00

**Comment by skalavala** [comment]
Where are you seeing that error? If you are trying that code n the template editor, you **will** get that error as it has not been triggered naturally, and the trigger object is not available in the template editor.

My birthday package used `input_label` custom component, and I assume you copied that code as well.

**Comment by abeksis** [comment]
The error appears when I try manually Today is the Birthday.

<img width="389" alt="screen shot 2019-02-08 at 07 45 12" src="https://user-images.githubusercontent.com/10877299/52460963-91df2880-2b75-11e9-8a15-6cce6250c5bf.png">
Another question - the count should show the general count? And not the time remaining until the birthday?
<img width="485" alt="screen shot 2019-02-08 at 07 57 30" src="https://user-images.githubusercontent.com/10877299/52461336-4ded2300-2b77-11e9-9bc1-a38191bcfa9d.png">
