### ISSUE TITLE
The error appears when I try manually Today is the Birthday.

### ISSUE THREAD

**Issue by abeksis** [skalavala/smarthome#46]
The error appears when I try manually Today is the Birthday.

<img width="389" alt="screen shot 2019-02-08 at 07 45 12" src="https://user-images.githubusercontent.com/10877299/52460963-91df2880-2b75-11e9-8a15-6cce6250c5bf.png">
Another question - the count should show the general count? And not the time remaining until the birthday?
<img width="485" alt="screen shot 2019-02-08 at 07 57 30" src="https://user-images.githubusercontent.com/10877299/52461336-4ded2300-2b77-11e9-9bc1-a38191bcfa9d.png">

_Originally posted by @abeksis in https://github.com/skalavala/smarthome/issues/45#issuecomment-461699905_

**Comment by skalavala** [comment]
If you try manually or in the template editor, you will get the error `trigger` is undefined. The automation has to naturally trigger for the automation to work. Manually triggering the automation would only cause error. Try changing the date of birth to today if you want it to trigger.

Also, the number you see if the number of days left - it is the count down. If your birthday is on Jan 10, and today is Jan 1, you should see the number as 10.

**Comment by abeksis** [comment]
These are birthday dates ..
nurit_birthday: "17-10"
rotam_birthday: "16-05"
liran_birthday: "25-08"

**Comment by skalavala** [comment]
The instructions are clear [in my repo](https://github.com/skalavala/smarthome/blob/master/packages/birthday.yaml#L11-L12) - The birthday format should be in `MM-DD`. In your case, it is set as `DD-MM`.
